spring:
  datasource:
    url: jdbc:h2:mem:movies
    username: zsut
    password: NagyTitok123
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /swagger-ui.html